### ISSUE TITLE
Problem about 'adaptive'

### ISSUE THREAD

**Issue by yxwang-10** [tribhuvanesh/knockoffnets#3]
Hello, I have read your paper, and I notice that the 'adaptive' strategy is interesting. But I found that you didn't implement the ‘adaptive’ strategy in your code. If you can tell me how to achieve this, I would appreciate it.

**Comment by sergevanhaag2** [comment]
It's not implemented yet, at least, not available to the public.

**Comment by yxwang-10** [comment]
@sergevanhaag Thank you very much for your kind reply
